// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'checkout_billing_shipping_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CheckoutBillingShippingData _$CheckoutBillingShippingDataFromJson(
        Map<String, dynamic> json) =>
    CheckoutBillingShippingData(
      userId: json['user_id'] as String?,
      status: json['status'] as String?,
      userType: json['user_type'] as String?,
      userLogin: json['user_login'] as String?,
      referer: json['referer'] as String?,
      isRoot: json['is_root'] as String?,
      companyId: json['company_id'] as String?,
      lastLogin: json['last_login'] as String?,
      lastActivity: json['last_activity'] as String?,
      timestamp: json['timestamp'] as String?,
      password: json['password'] as String?,
      salt: json['salt'] as String?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      company: json['company'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      fax: json['fax'] as String?,
      url: json['url'] as String?,
      taxExempt: json['tax_exempt'] as String?,
      langCode: json['lang_code'] as String?,
      birthday: json['birthday'] as String?,
      purchaseTimestampFrom: json['purchase_timestamp_from'] as String?,
      purchaseTimestampTo: json['purchase_timestamp_to'] as String?,
      responsibleEmail: json['responsible_email'] as String?,
      passwordChangeTimestamp: json['password_change_timestamp'] as String?,
      apiKey: json['api_key'] as String?,
      janrainIdentifier: json['janrain_identifier'] as String?,
      appliedPromotion: json['applied_promotion'] as String?,
      profileId: json['profile_id'] as String?,
      profileType: json['profile_type'] as String?,
      bFirstname: json['b_firstname'] as String?,
      bLastname: json['b_lastname'] as String?,
      bAddress: json['b_address'] as String?,
      bAddress2: json['b_address_2'] as String?,
      bCity: json['b_city'] as String?,
      bCounty: json['b_county'] as String?,
      bState: json['b_state'] as String?,
      bCountry: json['b_country'] as String?,
      bZipcode: json['b_zipcode'] as String?,
      bPhone: json['b_phone'] as String?,
      sFirstname: json['s_firstname'] as String?,
      sLastname: json['s_lastname'] as String?,
      sAddress: json['s_address'] as String?,
      sAddress2: json['s_address_2'] as String?,
      sCity: json['s_city'] as String?,
      sCounty: json['s_county'] as String?,
      sState: json['s_state'] as String?,
      sCountry: json['s_country'] as String?,
      sZipcode: json['s_zipcode'] as String?,
      sPhone: json['s_phone'] as String?,
      sAddressType: json['s_address_type'] as String?,
      profileName: json['profile_name'] as String?,
      profileUpdateTimestamp: json['profile_update_timestamp'] as String?,
      bCountryDescr: json['b_country_descr'] as String?,
      sCountryDescr: json['s_country_descr'] as String?,
      bStateDescr: json['b_state_descr'] as String?,
      sStateDescr: json['s_state_descr'] as String?,
      multipleProfileEnable: json['multiple_profile_enable'] as bool?,
      countryList: (json['country_list'] as List<dynamic>?)
          ?.map((e) => CountryList.fromJson(e as Map<String, dynamic>))
          .toList(),
      extra: json['extra'] == null
          ? null
          : Extra.fromJson(json['extra'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$CheckoutBillingShippingDataToJson(
        CheckoutBillingShippingData instance) =>
    <String, dynamic>{
      'user_id': instance.userId,
      'status': instance.status,
      'user_type': instance.userType,
      'user_login': instance.userLogin,
      'referer': instance.referer,
      'is_root': instance.isRoot,
      'company_id': instance.companyId,
      'last_login': instance.lastLogin,
      'last_activity': instance.lastActivity,
      'timestamp': instance.timestamp,
      'password': instance.password,
      'salt': instance.salt,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'company': instance.company,
      'email': instance.email,
      'phone': instance.phone,
      'fax': instance.fax,
      'url': instance.url,
      'tax_exempt': instance.taxExempt,
      'lang_code': instance.langCode,
      'birthday': instance.birthday,
      'purchase_timestamp_from': instance.purchaseTimestampFrom,
      'purchase_timestamp_to': instance.purchaseTimestampTo,
      'responsible_email': instance.responsibleEmail,
      'password_change_timestamp': instance.passwordChangeTimestamp,
      'api_key': instance.apiKey,
      'janrain_identifier': instance.janrainIdentifier,
      'applied_promotion': instance.appliedPromotion,
      'profile_id': instance.profileId,
      'profile_type': instance.profileType,
      'b_firstname': instance.bFirstname,
      'b_lastname': instance.bLastname,
      'b_address': instance.bAddress,
      'b_address_2': instance.bAddress2,
      'b_city': instance.bCity,
      'b_county': instance.bCounty,
      'b_state': instance.bState,
      'b_country': instance.bCountry,
      'b_zipcode': instance.bZipcode,
      'b_phone': instance.bPhone,
      's_firstname': instance.sFirstname,
      's_lastname': instance.sLastname,
      's_address': instance.sAddress,
      's_address_2': instance.sAddress2,
      's_city': instance.sCity,
      's_county': instance.sCounty,
      's_state': instance.sState,
      's_country': instance.sCountry,
      's_zipcode': instance.sZipcode,
      's_phone': instance.sPhone,
      's_address_type': instance.sAddressType,
      'profile_name': instance.profileName,
      'profile_update_timestamp': instance.profileUpdateTimestamp,
      'b_country_descr': instance.bCountryDescr,
      's_country_descr': instance.sCountryDescr,
      'b_state_descr': instance.bStateDescr,
      's_state_descr': instance.sStateDescr,
      'multiple_profile_enable': instance.multipleProfileEnable,
      'country_list': instance.countryList,
      'extra': instance.extra,
    };
