// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'required_products.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

RequiredProducts _$RequiredProductsFromJson(Map<String, dynamic> json) =>
    RequiredProducts(
      productId: json['product_id'] as String?,
      product: json['product'] as String?,
      productType: json['product_type'] as String?,
      parentProductId: json['parent_product_id'] as String?,
      masterProductOffersCount: json['master_product_offers_count'] as String?,
      masterProductId: json['master_product_id'] as String?,
      companyId: json['company_id'] as String?,
      productCode: json['product_code'] as String?,
      status: json['status'] as String?,
      listPrice: json['list_price'] as String?,
      amount: json['amount'] as String?,
      weight: json['weight'] as String?,
      length: json['length'] as String?,
      width: json['width'] as String?,
      height: json['height'] as String?,
      shippingFreight: json['shipping_freight'] as String?,
      lowAvailLimit: json['low_avail_limit'] as String?,
      timestamp: json['timestamp'] as String?,
      updatedTimestamp: json['updated_timestamp'] as String?,
      usergroupIds: json['usergroup_ids'] as String?,
      isEdp: json['is_edp'] as String?,
      edpShipping: json['edp_shipping'] as String?,
      unlimitedDownload: json['unlimited_download'] as String?,
      tracking: json['tracking'] as String?,
      freeShipping: json['free_shipping'] as String?,
      zeroPriceAction: json['zero_price_action'] as String?,
      isPbp: json['is_pbp'] as String?,
      isOp: json['is_op'] as String?,
      isOper: json['is_oper'] as String?,
      isReturnable: json['is_returnable'] as String?,
      returnPeriod: json['return_period'] as String?,
      availSince: json['avail_since'] as String?,
      outOfStockActions: json['out_of_stock_actions'] as String?,
      localization: json['localization'] as String?,
      minQty: json['min_qty'] as String?,
      maxQty: json['max_qty'] as String?,
      qtyStep: json['qty_step'] as String?,
      listQtyCount: json['list_qty_count'] as String?,
      taxIds: json['tax_ids'] as String?,
      ageVerification: json['age_verification'] as String?,
      ageLimit: json['age_limit'] as String?,
      optionsType: json['options_type'] as String?,
      exceptionsType: json['exceptions_type'] as String?,
      detailsLayout: json['details_layout'] as String?,
      shippingParams: json['shipping_params'] as String?,
      facebookObjType: json['facebook_obj_type'] as String?,
      buyNowUrl: json['buy_now_url'] as String?,
      masterProductStatus: json['master_product_status'] as String?,
      price: json['price'] as String?,
      categoryIds: (json['category_ids'] as List<dynamic>?)
          ?.map((e) => e as int)
          .toList(),
      optionsTypeRaw: json['options_type_raw'],
      exceptionsTypeRaw: json['exceptions_type_raw'],
      trackingRaw: json['tracking_raw'],
      zeroPriceActionRaw: json['zero_price_action_raw'],
      minQtyRaw: json['min_qty_raw'],
      maxQtyRaw: json['max_qty_raw'],
      qtyStepRaw: json['qty_step_raw'],
      listQtyCountRaw: json['list_qty_count_raw'],
      detailsLayoutRaw: json['details_layout_raw'] as String?,
      variationFeatures: (json['variation_features'] as List<dynamic>?)
          ?.map((e) => e as Object)
          .toList(),
      mainPair: json['main_pair'] == null
          ? null
          : MainPair.fromJson(json['main_pair'] as Map<String, dynamic>),
      basePrice: json['base_price'] as String?,
      selectedOptions: (json['selected_options1'] as List<dynamic>?)
          ?.map((e) => e as Object)
          .toList(),
      hasOptions: json['has_options'] as bool?,
      productOptions: (json['product_options'] as List<dynamic>?)
          ?.map((e) => e as Object)
          .toList(),
      discounts: json['discounts'] == null
          ? null
          : Discounts.fromJson(json['discounts'] as Map<String, dynamic>),
      qtyContent: (json['qty_content'] as List<dynamic>?)
          ?.map((e) => e as Object)
          .toList(),
      detailedParams: json['detailed_params'] == null
          ? null
          : DetailedParams.fromJson(
              json['detailed_params'] as Map<String, dynamic>),
      premoderationReason: json['premoderation_reason'] as String?,
      bought: json['bought'] as String?,
      itemId: json['item_id'],
    );

Map<String, dynamic> _$RequiredProductsToJson(RequiredProducts instance) =>
    <String, dynamic>{
      'product_id': instance.productId,
      'product': instance.product,
      'product_type': instance.productType,
      'parent_product_id': instance.parentProductId,
      'master_product_offers_count': instance.masterProductOffersCount,
      'master_product_id': instance.masterProductId,
      'company_id': instance.companyId,
      'product_code': instance.productCode,
      'status': instance.status,
      'list_price': instance.listPrice,
      'amount': instance.amount,
      'weight': instance.weight,
      'length': instance.length,
      'width': instance.width,
      'height': instance.height,
      'shipping_freight': instance.shippingFreight,
      'low_avail_limit': instance.lowAvailLimit,
      'timestamp': instance.timestamp,
      'updated_timestamp': instance.updatedTimestamp,
      'usergroup_ids': instance.usergroupIds,
      'is_edp': instance.isEdp,
      'edp_shipping': instance.edpShipping,
      'unlimited_download': instance.unlimitedDownload,
      'tracking': instance.tracking,
      'free_shipping': instance.freeShipping,
      'zero_price_action': instance.zeroPriceAction,
      'is_pbp': instance.isPbp,
      'is_op': instance.isOp,
      'is_oper': instance.isOper,
      'is_returnable': instance.isReturnable,
      'return_period': instance.returnPeriod,
      'avail_since': instance.availSince,
      'out_of_stock_actions': instance.outOfStockActions,
      'localization': instance.localization,
      'min_qty': instance.minQty,
      'max_qty': instance.maxQty,
      'qty_step': instance.qtyStep,
      'list_qty_count': instance.listQtyCount,
      'tax_ids': instance.taxIds,
      'age_verification': instance.ageVerification,
      'age_limit': instance.ageLimit,
      'options_type': instance.optionsType,
      'exceptions_type': instance.exceptionsType,
      'details_layout': instance.detailsLayout,
      'shipping_params': instance.shippingParams,
      'facebook_obj_type': instance.facebookObjType,
      'buy_now_url': instance.buyNowUrl,
      'master_product_status': instance.masterProductStatus,
      'price': instance.price,
      'category_ids': instance.categoryIds,
      'options_type_raw': instance.optionsTypeRaw,
      'exceptions_type_raw': instance.exceptionsTypeRaw,
      'tracking_raw': instance.trackingRaw,
      'zero_price_action_raw': instance.zeroPriceActionRaw,
      'min_qty_raw': instance.minQtyRaw,
      'max_qty_raw': instance.maxQtyRaw,
      'qty_step_raw': instance.qtyStepRaw,
      'list_qty_count_raw': instance.listQtyCountRaw,
      'details_layout_raw': instance.detailsLayoutRaw,
      'variation_features': instance.variationFeatures,
      'main_pair': instance.mainPair,
      'base_price': instance.basePrice,
      'selected_options1': instance.selectedOptions,
      'has_options': instance.hasOptions,
      'product_options': instance.productOptions,
      'discounts': instance.discounts,
      'qty_content': instance.qtyContent,
      'detailed_params': instance.detailedParams,
      'premoderation_reason': instance.premoderationReason,
      'bought': instance.bought,
      'item_id': instance.itemId,
    };
