// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'profileUserModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProfileUserModel _$ProfileUserModelFromJson(Map<String, dynamic> json) =>
    ProfileUserModel(
      userId: json['user_id'] as String?,
      status: json['status'] as String?,
      userType: json['user_type'] as String?,
      userLogin: json['user_login'] as String?,
      referer: json['referer'] as String?,
      isRoot: json['is_root'] as String?,
      companyId: json['company_id'] as String?,
      password: json['password'] as String?,
      firstname: json['firstname'] as String?,
      lastname: json['lastname'] as String?,
      company: json['company'] as String?,
      email: json['email'] as String?,
      phone: json['phone'] as String?,
      fax: json['fax'] as String?,
      url: json['url'] as String?,
      taxExempt: json['tax_exempt'] as String?,
      langCode: json['lang_code'] as String?,
      externalId: json['external_id'] as String?,
      appliedPromotion: json['applied_promotion'] as String?,
      profileId: json['profile_id'] as String?,
      profileType: json['profile_type'] as String?,
      bFirstname: json['b_firstname'] as String?,
      bLastname: json['b_lastname'] as String?,
      bAddress: json['b_address'] as String?,
      bAddress2: json['b_address_2'] as String?,
      bCity: json['b_city'] as String?,
      bState: json['b_state'] as String?,
      bCountry: json['b_country'] as String?,
      bZipcode: json['b_zipcode'] as String?,
      bPhone: json['b_phone'] as String?,
      sFirstname: json['s_firstname'] as String?,
      sLastname: json['s_lastname'] as String?,
      sAddress: json['s_address'] as String?,
      sAddress2: json['s_address_2'] as String?,
      sCity: json['s_city'] as String?,
      sState: json['s_state'] as String?,
      sCountry: json['s_country'] as String?,
      sZipcode: json['s_zipcode'] as String?,
      sPhone: json['s_phone'] as String?,
      sAddressType: json['s_address_type'] as String?,
      profileName: json['profile_name'] as String?,
      bCountryDescr: json['b_country_descr'] as String?,
      sCountryDescr: json['s_country_descr'] as String?,
      bStateDescr: json['b_state_descr'] as String?,
      sStateDescr: json['s_state_descr'] as String?,
      points: json['points'] as int?,
      isSelected: json['isSelected'] as bool?,
      shipToAnother: json['ship_to_another'] as int?,
    )
      ..success = json['success'] as bool?
      ..message = json['message'] as String?
      ..error = json['error']
      ..msg = json['msg'] as String?;

Map<String, dynamic> _$ProfileUserModelToJson(ProfileUserModel instance) =>
    <String, dynamic>{
      'success': instance.success,
      'message': instance.message,
      'error': instance.error,
      'msg': instance.msg,
      'user_id': instance.userId,
      'status': instance.status,
      'user_type': instance.userType,
      'user_login': instance.userLogin,
      'referer': instance.referer,
      'is_root': instance.isRoot,
      'company_id': instance.companyId,
      'password': instance.password,
      'firstname': instance.firstname,
      'lastname': instance.lastname,
      'company': instance.company,
      'email': instance.email,
      'phone': instance.phone,
      'fax': instance.fax,
      'url': instance.url,
      'tax_exempt': instance.taxExempt,
      'lang_code': instance.langCode,
      'external_id': instance.externalId,
      'applied_promotion': instance.appliedPromotion,
      'profile_id': instance.profileId,
      'profile_type': instance.profileType,
      'b_firstname': instance.bFirstname,
      'b_lastname': instance.bLastname,
      'b_address': instance.bAddress,
      'b_address_2': instance.bAddress2,
      'b_city': instance.bCity,
      'b_state': instance.bState,
      'b_country': instance.bCountry,
      'b_zipcode': instance.bZipcode,
      'b_phone': instance.bPhone,
      's_firstname': instance.sFirstname,
      's_lastname': instance.sLastname,
      's_address': instance.sAddress,
      's_address_2': instance.sAddress2,
      's_city': instance.sCity,
      's_state': instance.sState,
      's_country': instance.sCountry,
      's_zipcode': instance.sZipcode,
      's_phone': instance.sPhone,
      's_address_type': instance.sAddressType,
      'profile_name': instance.profileName,
      'b_country_descr': instance.bCountryDescr,
      's_country_descr': instance.sCountryDescr,
      'b_state_descr': instance.bStateDescr,
      's_state_descr': instance.sStateDescr,
      'points': instance.points,
      'ship_to_another': instance.shipToAnother,
      'isSelected': instance.isSelected,
    };
